### ISSUE TITLE
RSpec::Matchers.define should define argument 0

### ISSUE THREAD

**Issue by robotdana** [robotdana/leftovers#15]
```yml
name: define
has_receiver:
  match: Matchers
  has_receiver: RSpec
defines:
  argument: 0
```
