### ISSUE TITLE
:wave: Not directly called at all in model with_options validation

### ISSUE THREAD

**Issue by dtbaker** [robotdana/leftovers#20]
Heya, we spotted this:

```
Not directly called at all:
app/models/foo.rb:6:7 published? def published?

```

```
class Foo < ApplicationRecord
  with_options if: :published? do
    validates :bar, presence: true
  end

  def published?
    state == States::PUBLISHED
  end
end
```

it was only an issue for a few seconds as we added code to call `published?` elsewhere, but on its own it came up as unused.

**Comment by robotdana** [comment]
hey thanks :) unfortunately with_options can’t be supported without significant changes to how things work, i’ll add a note to the limitations section of the readme.

**Comment by dtbaker** [comment]
Some pat magic:

```
dynamic:
  # ActiveSupport's `Object#with_options` as used in ActiveModel validations:
  # https://api.rubyonrails.org/classes/Object.html#method-i-with_options
  # e.g. `with_options if: :published?` will call `#published?`
  - name: with_options
    call:
      arguments: # with_options accepts any arbitrary hash of options. Feel free to add any keywords we use with it here.
        - if
```
