### ISSUE TITLE
calls does not recognize qualified constant name with document: true

### ISSUE THREAD

**Issue by such** [robotdana/leftovers#26]
Here is a minimal repository that reproduces the issue: https://github.com/such/leftovers_test

with a yml document such as:

```
class_name:
  - Foo::Bar
  - Baz
```

and a dynamic config such as:

```
dynamic:
  - document: true
    path: test.yml
    calls:
      argument: class_name
      nested:
        argument: '*'
```

`Foo::Bar` is not marked as called
`Baz` is correctly marked as called

**Comment by robotdana** [comment]
you’ll need to add `split: "::"` as it’s just doing string matching on the values:
e.g.

```
dynamic:
  - document: true
    path: test.yml
    calls:
      argument: class_name
      split: '::'
      nested:
        argument: '*'
```
